name: Test Action
on:
  push:
    branches:
      - master
jobs:
  test:
    name: 测试
    runs-on: ubuntu-latest
    steps:
    - name: 更新代码
      uses: actions/checkout@master
    
    - name: 测试报错
      run: node start

    - name: 发送邮件
      if: always()
      uses: ./
      with:
        user: '${{ secrets.MAIL_USER }}'
        pass: '${{ secrets.MAIL_PASS }}'
        to: 895355044@qq.com,xiaomucool@bingblue.com
        subject: '[滨清科技] --> ${{ github.repository }}项目构建结果'
        github: ${{ toJson(github) }}
        success: ${{ job.status }}
